/* Generated by Yosys 0.50 (git sha1 b5170e1394f602c607e75bdbb1a2b637118f2086, clang++ 16.0.0 -fPIC -O3) */

(* hdlname = "counter" *)
(* top =  1  *)
(* src = "src/aes/counter.v:3.1-30.10" *)
module counter(clk, rst_n, start, stop, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  (* force_downto = 32'd1 *)
  (* src = "src/aes/counter.v:25.16-25.26|/opt/homebrew/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  (* src = "src/aes/counter.v:4.17-4.20" *)
  input clk;
  wire clk;
  (* src = "src/aes/counter.v:8.23-8.28" *)
  output [3:0] count;
  wire [3:0] count;
  (* src = "src/aes/counter.v:5.17-5.22" *)
  input rst_n;
  wire rst_n;
  (* src = "src/aes/counter.v:6.17-6.22" *)
  input start;
  wire start;
  (* src = "src/aes/counter.v:11.5-11.10" *)
  wire state;
  (* src = "src/aes/counter.v:7.17-7.21" *)
  input stop;
  wire stop;
  (* src = "src/aes/counter.v:12.11-12.14" *)
  wire [3:0] val;
  INV_X1 _19_ (
    .A(_14_[0]),
    .ZN(_05_)
  );
  INV_X1 _20_ (
    .A(rst_n),
    .ZN(_06_)
  );
  NOR2_X1 _21_ (
    .A1(state),
    .A2(val[0]),
    .ZN(_07_)
  );
  AOI211_X1 _22_ (
    .A(_06_),
    .B(_07_),
    .C1(state),
    .C2(_05_),
    .ZN(_00_)
  );
  AND3_X1 _23_ (
    .A1(state),
    .A2(val[1]),
    .A3(val[0]),
    .ZN(_08_)
  );
  AOI21_X1 _24_ (
    .A(val[1]),
    .B1(val[0]),
    .B2(state),
    .ZN(_09_)
  );
  NOR3_X1 _25_ (
    .A1(_06_),
    .A2(_08_),
    .A3(_09_),
    .ZN(_01_)
  );
  AND4_X1 _26_ (
    .A1(state),
    .A2(val[2]),
    .A3(val[1]),
    .A4(val[0]),
    .ZN(_10_)
  );
  OAI21_X1 _27_ (
    .A(rst_n),
    .B1(_08_),
    .B2(val[2]),
    .ZN(_11_)
  );
  NOR2_X1 _28_ (
    .A1(_10_),
    .A2(_11_),
    .ZN(_02_)
  );
  OAI21_X1 _29_ (
    .A(rst_n),
    .B1(_10_),
    .B2(val[3]),
    .ZN(_12_)
  );
  AOI21_X1 _30_ (
    .A(_12_),
    .B1(_10_),
    .B2(val[3]),
    .ZN(_03_)
  );
  OAI21_X1 _31_ (
    .A(rst_n),
    .B1(start),
    .B2(state),
    .ZN(_13_)
  );
  NOR2_X1 _32_ (
    .A1(stop),
    .A2(_13_),
    .ZN(_04_)
  );
  (* src = "src/aes/counter.v:21.1-26.4" *)
  DFF_X1 _33_ (
    .CK(clk),
    .D(_00_),
    .Q(val[0]),
    .QN(_14_[0])
  );
  (* src = "src/aes/counter.v:21.1-26.4" *)
  DFF_X1 _34_ (
    .CK(clk),
    .D(_01_),
    .Q(val[1]),
    .QN(_18_)
  );
  (* src = "src/aes/counter.v:21.1-26.4" *)
  DFF_X1 _35_ (
    .CK(clk),
    .D(_02_),
    .Q(val[2]),
    .QN(_17_)
  );
  (* src = "src/aes/counter.v:21.1-26.4" *)
  DFF_X1 _36_ (
    .CK(clk),
    .D(_03_),
    .Q(val[3]),
    .QN(_16_)
  );
  (* src = "src/aes/counter.v:14.1-19.4" *)
  DFF_X1 _37_ (
    .CK(clk),
    .D(_04_),
    .Q(state),
    .QN(_15_)
  );
  assign _14_[3:1] = val[3:1];
  assign count = val;
endmodule
